sudo: false
os:
  - linux
  - osx
language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv run pip install codecov
script:
  - nosetests --with-coverage
after_success:
  - codecov
notifications:
  email:
    on_success: never
    on_failure: always
