sudo: false
language: python
python:
  - 3.0
  - 3.1
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7
install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv run pip install codecov
script:
  - nosetests --with-coverage
after_success:
  - codecov
notifications:
  email:
    on_success: never
    on_failure: always
